Default:
  25,1,0:
    - type: SKELETON
      count: 15
    - type: ZOMBIE
      count: 15
  25,1,25:
    - type: SKELETON
      count: 7
    - type: ZOMBIE
      count: 7
    - type: CREEPER
      count: 5
  0,1,25:
    - type: SKELETON
      count: 15
    - type: ZOMBIE
      count: 15
  -25,1,25:
    - type: SKELETON
      count: 7
    - type: ZOMBIE
      count: 7
    - type: CREEPER
      count: 5
  -25,1,0:
    - type: SKELETON
      count: 15
    - type: ZOMBIE
      count: 15
  -25,1,-25:
    - type: SKELETON
      count: 7
    - type: ZOMBIE
      count: 7
    - type: CREEPER
      count: 5
  0,1,-25:
    - type: SKELETON
      count: 15
    - type: ZOMBIE
      count: 15
  25,1,-25:
    - type: SKELETON
      count: 7
    - type: ZOMBIE
      count: 7
    - type: CREEPER
      count: 5
  0,60,0:
    - type: PHANTOM
      count: 20
#   50,2,0:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   50,2,25:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   50,2,50:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   25,2,50:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   0,2,50:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   -25,2,50:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   -50,2,50:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   -50,2,25:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   -50,2,0:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   -50,2,-25:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   -50,2,-50:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   -25,2,-50:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   0,2,-50:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   25,2,-50:
#     - type: SKELETON
#       count: 20
#     - type: ZOMBIE
#       count: 20
#   50,2,-50:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   50,2,-25:
#     - type: SKELETON
#       count: 10
#     - type: ZOMBIE
#       count: 10
#     - type: CREEPER
#       count: 5
#   0,3,80:
#     - type: ENDERMAN
#       count: 30
#   0,3,-80:
#     - type: WITCH
#       count: 30
#   80,3,0:
#     - type: EVOKER
#       count: 15
#     - type: RAVAGER
#       count: 5
#   -80,3,0:
#     - type: SLIME
#       count: 30