Default:
  100,1,100:
    - type: ZOMBIE
      count: 10
    - type: SKELETON
      count: 10
  -100,1,-100:
    - type: ZOMBIE
      count: 20
#  100,1,0:
#    - type: ZOMBIE
#      count: 10
#    - type: SKELETON
#      count: 10
#  -100,1,0:
#    - type: ZOMBIE
#      count: 10
#    - type: SKELETON
#      count: 10
#  -100,1,100:
#    - type: ZOMBIE
#      count: 10
#    - type: SKELETON
#      count: 10
#  100,1,-100:
#    - type: ZOMBIE
#      count: 10
#    - type: SKELETON
#      count: 10
#  -100,1,-100:
#    - type: ZOMBIE
#      count: 10
#    - type: SKELETON
#      count: 10
#  100,1,100:
#    - type: ZOMBIE
#      count: 10
#    - type: SKELETON
#      count: 10