name: BedrockPvE
version: '${project.version}'
main: net.azisaba.afnw.bedrockPvE.BedrockPvE
api-version: 1.17
authors: [ 5hak3 ]
description: Bedrock PvE in AFNW!

permissions:
  bpe.op:
    default: op

commands:
  bpetestspawn:
    description: Spawn MOB Test.
    permission: bpe.op
    permission-message: "This command is ONLY available to operators."
  bpespawn:
    description: Spawn MOBs in Bedrock PvE World.
    permission: bpe.op
    permission-message: "This command is ONLY available to operators."
  bpereload:
    description: Reload config.yml.
    permission: bpe.op
    permission-message: "This command is ONLY available to operators."
  bpe:
    description: Bedrock PvE Worldへ移動！
