name: BedrockPvE
version: '${project.version}'
main: com.github.afnw.bedrockPvE.BedrockPvE
api-version: 1.17
authors: [ 5hak3 ]
description: Bedrock PvE in AFNW!

permissions:
  bpe.op:
    default: op

commands:
  bpespawn:
    description: Spawn MOBs in Bedrock PvE World.
    permission: bpe.op
    permission-message: "This command is ONLY available to operators."